[2025-02-03T17:48:02.738+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_dag.extract_task manual__2025-02-03T17:48:00.389253+00:00 [queued]>
[2025-02-03T17:48:02.742+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_dag.extract_task manual__2025-02-03T17:48:00.389253+00:00 [queued]>
[2025-02-03T17:48:02.742+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2025-02-03T17:48:02.753+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): extract_task> on 2025-02-03 17:48:00.389253+00:00
[2025-02-03T17:48:02.756+0000] {standard_task_runner.py:57} INFO - Started process 163059 to run task
[2025-02-03T17:48:02.758+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'extract_dag', 'extract_task', 'manual__2025-02-03T17:48:00.389253+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/extract_dag.py', '--cfg-path', '/tmp/tmpvubv5uia']
[2025-02-03T17:48:02.758+0000] {standard_task_runner.py:85} INFO - Job 10: Subtask extract_task
[2025-02-03T17:48:02.782+0000] {task_command.py:410} INFO - Running <TaskInstance: extract_dag.extract_task manual__2025-02-03T17:48:00.389253+00:00 [running]> on host codespaces-039a13
[2025-02-03T17:48:02.828+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='extract_dag' AIRFLOW_CTX_TASK_ID='extract_task' AIRFLOW_CTX_EXECUTION_DATE='2025-02-03T17:48:00.389253+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-03T17:48:00.389253+00:00'
[2025-02-03T17:48:02.829+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-02-03T17:48:02.829+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'wget -c https://https://raw.githubusercontent.com/LinkedInLearning/hands-on-introduction-data-engineering-4395021/main/data/top-level-domain-names.csv -O /workspaces/hands-on-introduction-data-engineering-4395021/lab/orchestrated/airflow-extract-data.csv']
[2025-02-03T17:48:02.835+0000] {subprocess.py:86} INFO - Output:
[2025-02-03T17:48:02.839+0000] {subprocess.py:93} INFO - --2025-02-03 17:48:02--  https://https//raw.githubusercontent.com/LinkedInLearning/hands-on-introduction-data-engineering-4395021/main/data/top-level-domain-names.csv
[2025-02-03T17:48:02.866+0000] {subprocess.py:93} INFO - Resolving https (https)... failed: Name or service not known.
[2025-02-03T17:48:02.866+0000] {subprocess.py:93} INFO - wget: unable to resolve host address ‘https’
[2025-02-03T17:48:02.866+0000] {subprocess.py:97} INFO - Command exited with return code 4
[2025-02-03T17:48:02.873+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 4.
[2025-02-03T17:48:02.875+0000] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=extract_dag, task_id=extract_task, execution_date=20250203T174800, start_date=20250203T174802, end_date=20250203T174802
[2025-02-03T17:48:02.887+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 10 for task extract_task (Bash command failed. The command returned a non-zero exit code 4.; 163059)
[2025-02-03T17:48:02.929+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2025-02-03T17:48:02.938+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
